Repository BitVivek/COMP367_Groupproject, pull requests merged in 2024-12, with the labels that each got.

#3 Added validation for appointment creation
  .idea/.name
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: enhancement, validation

#6 ADDED Test case which were failing - issue
  controllers/generalController.js
  tests/generalController.test.js
Labels: issue, resolved

#7 updated code fir validation
  .idea/.name
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  azure-pipelines.yml
  controllers/appointmentController.js
  controllers/doctorController.js
  controllers/patientController.js
  package.json
  sonar-project.properties
Labels: enhancement
